# Generated by Django 2.2.6 on 2020-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='jobpost')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('des', models.TextField()),
                ('job_nature', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('tag_1', models.CharField(max_length=100)),
                ('tag_2', models.CharField(max_length=100)),
                ('tag_3', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
