# Generated by Django 2.2.6 on 2020-04-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anshaj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
