# Generated by Django 2.2.6 on 2020-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anshaj', '0003_applyed_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='imp_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
